-- Migration: Restructure locations table
-- - Remove url_param, branch_name, is_active
-- - Add postal_code
-- - Reload all GBH branches from locations_final.json

-- 1. Drop removed columns, add postal_code
ALTER TABLE locations DROP COLUMN IF EXISTS url_param;
ALTER TABLE locations DROP COLUMN IF EXISTS branch_name;
ALTER TABLE locations DROP COLUMN IF EXISTS is_active;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS postal_code VARCHAR(10);

-- 2. Clear existing data
TRUNCATE TABLE locations RESTART IDENTITY CASCADE;

-- 3. Re-insert all GBH branches
INSERT INTO locations (retailer_id, name_th, name_en, branch_code, postal_code) VALUES
('gbh', 'ร้อยเอ็ด',                        'ROI ET',                         'GH-101', '45000'),
('gbh', 'ขอนแก่น',                          'KHON KAEN',                      'GH-102', '40000'),
('gbh', 'อุดรธานี',                          'UDON THANI',                     'GH-103', '41000'),
('gbh', 'เวียงกุมกาม',                       'WIANGKUMKAM',                    'GH-104', '50140'),
('gbh', 'ระยอง',                             'RAYONG',                         'GH-105', '21000'),
('gbh', 'ชลบุรี',                            'CHONBURI',                       'GH-106', '20000'),
('gbh', 'นครปฐม',                            'NAKHONPATHOM',                   'GH-107', '73000'),
('gbh', 'ราชบุรี',                           'RATCHABURI',                     'GH-108', '70000'),
('gbh', 'กาฬสินธุ์',                         'KALASIN',                        'GH-109', '46000'),
('gbh', 'นครสวรรค์',                         'NAKORNSAWAN',                    'GH-110', '60240'),
('gbh', 'มหาสารคาม',                         'MAHASARAKAM',                    'GH-112', '44000'),
('gbh', 'บ้านไผ่',                           'BANPAI',                         'GH-113', '40110'),
('gbh', 'หนองคาย',                           'NONGKHAI',                       'GH-114', '43000'),
('gbh', 'นครราชสีมา',                        'NAKORNRAJCHASIMA',               'GH-115', '30000'),
('gbh', 'สกลนคร',                            'SAKON NAKHON',                   'GH-116', '47000'),
('gbh', 'นครพนม',                            'NAKHON PHANOM',                  'GH-117', '48000'),
('gbh', 'ชัยภูมิ',                           'CHAIYAPHOOM',                    'GH-118', '36000'),
('gbh', 'สุรินทร์',                          'SURIN',                          'GH-119', '32000'),
('gbh', 'พิษณุโลก',                          'PHITSANULOK',                    'GH-120', '65000'),
('gbh', 'ลำพูน',                             'LAMPHUN',                        'GH-121', '51000'),
('gbh', 'มุกดาหาร',                          'MUKDAHAN',                       'GH-122', '49000'),
('gbh', 'ประจวบคีรีขันธ์',                   'PRACHUAP KHIRI KHAN',            'GH-123', '77000'),
('gbh', 'ลำปาง',                             'LAMPANG',                        'GH-124', '52000'),
('gbh', 'แพร่',                              'PHRAE',                          'GH-125', '54130'),
('gbh', 'น่าน',                              'NAN',                            'GH-126', '55000'),
('gbh', 'เชียงราย',                          'CHIANGRAI',                      'GH-127', '57000'),
('gbh', 'สุโขทัย',                           'SUKHOTHAI',                      'GH-128', '64000'),
('gbh', 'อุบลราชธานี',                       'UBON RATCHATHANI',               'GH-129', '34190'),
('gbh', 'กำแพงเพชร',                         'KAMPHAENG PHET',                 'GH-130', '62000'),
('gbh', 'เพชรบูรณ์',                         'PHETCHABUN',                     'GH-131', '67000'),
('gbh', 'ลพบุรี',                            'LOPBURI',                        'GH-132', '15000'),
('gbh', 'จันทบุรี',                          'CHANTHABURI',                    'GH-135', '22120'),
('gbh', 'ตราด',                              'TRAT',                           'GH-136', '23000'),
('gbh', 'บ้านตาด',                           'BANTAD',                         'GH-137', '41000'),
('gbh', 'พะเยา',                             'PHAYAO',                         'GH-138', '56000'),
('gbh', 'บุรีรัมย์',                         'BURI RAM',                       'GH-139', '31000'),
('gbh', 'ปราณบุรี',                          'PRANBURI',                       'GH-140', '77120'),
('gbh', 'เทพารักษ์',                         'THEPHARAK',                      'GH-141', '10540'),
('gbh', 'หนองบัวลำภู',                       'NONG BUA LAM PHU',               'GH-142', '39000'),
('gbh', 'สมุทรสงคราม',                       'SAMUT SONGKHRAM',                'GH-144', '75000'),
('gbh', 'พระนครศรีอยุธยา',                   'PHRA NAKHON SI AYUTTHAYA',       'GH-145', '13160'),
('gbh', 'นครนายก',                           'NAKHON NAYOK',                   'GH-146', '26000'),
('gbh', 'ปทุมธานี',                          'PATHUMTHANI',                    'GH-150', '12160'),
('gbh', 'ศาลายา',                            'SALAYA',                         'GH-151', '73210'),
('gbh', 'นครศรีธรรมราช',                     'NAKHONSITHAMMARAT',              'GH-152', '80000'),
('gbh', 'บึงกาฬ',                            'BUNGKAN',                        'GH-153', '38000'),
('gbh', 'สุราษฎร์ธานี',                      'SURATTHANI',                     'GH-154', '84000'),
('gbh', 'กาญจนบุรี',                         'KANCHANABURI',                   'GH-155', '71000'),
('gbh', 'สิงห์บุรี',                         'SINGBURI',                       'GH-156', '16000'),
('gbh', 'ยโสธร',                             'YASOTHON',                       'GH-158', '35000'),
('gbh', 'อ่างทอง',                           'ANGTHONG',                       'GH-159', '14000'),
('gbh', 'เลย',                               'LOEI',                           'GH-160', '42000'),
('gbh', 'พัทลุง',                            'PHATTHALUNG',                    'GH-161', '93000'),
('gbh', 'อุตรดิตถ์',                         'UTTARADIT',                      'GH-162', '53000'),
('gbh', 'ชุมแพ',                             'CHUM PHAE',                      'GH-163', '40130'),
('gbh', 'ภูเก็ต',                            'PHUKET',                         'GH-164', '83130'),
('gbh', 'แม่สาย',                            'MAESAI',                         'GH-166', '57130'),
('gbh', 'พังโคน',                            'PHANG KHON',                     'GH-168', '47160'),
('gbh', 'แม่ฮ่องสอน',                        'MAEHONGSON',                     'GH-169', '58000'),
('gbh', 'โชคชัย',                            'CHOKCHAI',                       'GH-171', '30190'),
('gbh', 'ชัยนาท',                            'CHAINAT',                        'GH-172', '17000'),
('gbh', 'ฝาง',                               'FANG',                           'GH-173', '50110'),
('gbh', 'ด่านขุนทด',                         'DAN KHUN THOT',                  'GH-174', '30210'),
('gbh', 'สตูล',                              'SATUN',                          'GH-175', '91140'),
('gbh', 'เดชอุดม',                           'DET UDOM',                       'GH-176', '34160'),
('gbh', 'กันทรลักษ์',                        'KANTHARALAK',                    'GH-177', '33110'),
('gbh', 'นางรอง',                            'NANGRONG',                       'GH-178', '31110'),
('gbh', 'ไทรน้อย',                           'SAINOI',                         'GH-179', '11150'),
('gbh', 'หนองหาน',                           'NONGHAN',                        'GH-182', '41130'),
('gbh', 'กระทุ่มแบน',                        'KRATHUMBAEN',                    'GH-183', '74110'),
('gbh', 'พยัคฆภูมิพิสัย',                   'PHAYAKKHAPHUM PHISAI',           'GH-184', '44110'),
('gbh', 'กบินทร์บุรี',                       'KABINBURI',                      'GH-185', '25240'),
('gbh', 'กุฉินารายณ์',                       'KUCHINARAI',                     'GH-186', '46110'),
('gbh', 'สมุย',                              'SAMUI',                          'GH-187', '84330'),
('gbh', 'พาน',                               'PHAN',                           'GH-188', '57120'),
('gbh', 'เวียงป่าเป้า',                      'WIANG PA PAO',                   'GH-189', '57170'),
('gbh', 'จะนะ',                              'CHANA',                          'GH-191', '90130'),
('gbh', 'พิจิตร',                            'PHICHIT',                        'GH-192', '66000'),
('gbh', 'พรเจริญ',                           'PORNCHAROEN',                    'GH-193', '38180'),
('gbh', 'ระนอง',                             'RANONG',                         'GH-194', '85000'),
('gbh', 'โพนทอง',                            'PHONTHONG',                      'GH-195', '45110'),
('gbh', 'เลิงนกทา',                          'LOENG NOK THA',                  'GH-197', '35120'),
('gbh', 'ปัตตานี',                           'PATTANI',                        'GH-198', '94000'),
('gbh', 'ลาดยาว',                            'LAT YAO',                        'GH-199', '60150'),
('gbh', 'ชุมพร',                             'CHUMPHON',                       'GH-200', '86000'),
('gbh', 'พิมาย',                             'PHIMAI',                         'GH-201', '30110'),
('gbh', 'นราธิวาส',                          'NARATHIWAT',                     'GH-202', '96180'),
('gbh', 'กระนวน',                            'KRANUAN',                        'GH-203', '40170'),
('gbh', 'สว่างแดนดิน',                       'SAWANG DAEN DIN',                'GH-206', '47110'),
('gbh', 'ลำปลายมาศ',                         'LAM PLAI MAT',                   'GH-207', '31130'),
('gbh', 'สวรรคโลก',                          'SAWAN KHALOK',                   'GH-209', '64110'),
('gbh', 'บ้านดุง',                           'BAN DUNG',                       'GH-210', '41190'),
('gbh', 'เดอะไนน์เซ็นเตอร์ติวานนท์',        'THE NINE CENTER TIWANON',        'GH-211', '12000'),
('gbh', 'สมเด็จ',                            'SOMDET',                         'GH-212', '46150'),
('gbh', 'เวียงสา',                           'WSA',                            'GH-213', '55110'),
('gbh', 'แม่สอด',                            'MAESOT',                         'GH-214', '63110');
